USE gama_sed;
INSERT INTO run (run_id, description) VALUES (1, 'Run base on the file new20band.dat from 19 Dec 2013');

INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'fuv'     , 0.1535, 123);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'nuv'     , 0.2301, 124);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'u'       , 0.3557, 115);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'g'       , 0.4702, 116);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'r'       , 0.6175, 117);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'i'       , 0.7491, 118);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'Z'       , 0.8800, 318);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'Y'       , 1.0213, 319);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'J'       , 1.2525, 320);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'H'       , 1.6433, 321);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'K'       , 2.1503, 322);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'WISEW1'  , 3.4   , 280);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'WISEW2'  , 4.6   , 281);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'WISEW3'  , 12.   , 282);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'WISEW4'  , 22.   , 283);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'PACS100' , 100.  , 170);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'PACS160' , 160.  , 171);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'SPIRE250', 250.  , 172);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'SPIRE350', 350.  , 173);
INSERT INTO filter (run_id, name, eff_lambda, filter_number) VALUES (1, 'SPIRE500', 500.  , 174);
